<?php
 $deliveryFeeId = $this->getCheckout()->getQuote()->getDeliveryFeeId();
 $deliveryOptions= $this->getDeliveryFeeOptions();
 if(!empty($deliveryOptions)):
 ?>
<div class="delivery-fee-wrap">
<h5><?php echo $this->getDeliveryFeeLabel()?></h5>   
    <ul>   
<?php $j=1; foreach($deliveryOptions as $_option):   ?>
        <li>
        <input type="radio" id="delivery-fee:<?php echo $_option['id']; ?>" name="deliveryfee" value="<?php echo $_option['id']; ?>"<?php echo ($_option['id']==$deliveryFeeId || $j==1)?'checked="checked"':''; ?>/>
        <label for="delivery-fee:<?php echo $_option['id']; ?>"><?php 
		$_label = $this->__($_option['label']);
		$regex='/\[(.*)\]/i';
		if(preg_match($regex, $_label, $matches)){
			$days = $matches[1];
			if(stripos($days,'+')===false && (int)$days>0)$days='+'.$days;
			$days = date('Y-m-d',strtotime("$days days"));
			$_label=str_replace($matches[0],$days,$_label);
		}
		echo $_label;
		?></label>
        <div class="delivery-fee-description"><?php echo $_option['description']; ?></div>
        <?php if($_option['price']>0):  ?>
        <div class="delivery-fee-price"><?php echo Mage::App()->getStore()->convertPrice($_option['price'],true); ?></div>
        <?php endif;  ?>
        </li>
<?php $j++;endforeach; ?>
    </ul> 
</div>
<?php endif; ?>