<?php
/**
 * Moo Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Moo
 * @package    Moo_Catalog
 * @author     Mohamed Alsharaf <mohamed.alsharaf@gmail.com>
 * @copyright  Copyright (c) 2010 Mohamed Alsharaf. (http://jamandcheese-on-phptoast.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 
多图格式：show as picture-sapphire

1\ $_image->getLabel()  在后台加标示，原来的label|||color 
2\ 图片加一张小图，专门给色卡上的正方形图使用，与色卡正方形一致
3\ 点击show as pic 小图，找到对应的颜色图，没有/第一条，找到父dom li>a，加trigger click
*/
 
 
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 0) {
    $gallery = '<div class="more-views lof-slidecontent" id="lofslidecontent45">';
    //$gallery .= '<h2>' . $this->__('More Views') . '</h2>';
     $gallery .= '<div class="lof-navigator-wapper"><div onclick="return false" class="lof-next">&nbsp;</div><div class="lof-navigator-outer">';
    
    $gallery .= '<ul class="lof-navigator">';

     // 添加属性图片 开始
    $attr_gallery = '<div style="display:none" id="lof-navigator"><ul>';

    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li class="">'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(72,96) . '" width="62" height="85" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '<em class="arrow"></em></a></li>';
				// $gallery .= '<div style="display:none;" id="cloudZoomAs"><img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(170,170) . '"/></div>';
				// $gallery .= '</li>';

        $attr_gallery  .= '<li>'        
                       .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(170,170) . '"  bigsrc="' . $this->getCloudImage($this->getProduct(), $_image) .  '" alt="' . $this->htmlEscape($_image->getLabel()) . '"/>'        
                       .  '</li>';        

				 
    }
    $gallery .= '<li class="product-gallery-li-next">&nbsp;</li>';
    $gallery .= '</ul></div>';
    
    $gallery .= '<div onclick="return false" class="lof-previous">&nbsp;</div></div></div>';  

    // 添加属性图片结束
    $attr_gallery .= '</ul></div>';
}
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom" style=" z-index: 100;">
  <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
    <?php
        $_img = '<img id="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" width="420" height="560"/>';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    </a>
</p>




    <?php if(isset($gallery)): ?>
        <?php echo $gallery; ?>
    <?php endif; ?>

    <!-- 添加属性图片 -->
     <?php if(isset($gallery)): ?>
        <?php echo $attr_gallery; ?>
    <?php endif; ?>   

<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>


