<?php
/**
 * BelVG
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 
 * @category   Belvg
 * @package    Chameleon Mobile Theme
 * @copyright  Copyright (c) 2010 - 2012 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <div class="sort-by">
			<span class="sort-by-arrow">
			<label for="sort_by"><?php echo $this->__('Sort:') ?></label>
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a class="order asc" href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>">&nbsp;</a>
            <?php else: ?>
                <a class="order desc" href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>">&nbsp;</a>
            <?php endif; ?>
			 </span>
			 
            <span class="sort-by-wrap">				
            <ul id="sort_by" onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <li><a href="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?></a>
                </li>
            <?php endforeach; ?>
            </ul>
            </span>
        </div>
    </div>
    <?php endif; ?>
	    <div class="pager">
        <p class="amount" style="display:none;">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('%s-%s/%s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </p>

        <?php echo $this->getPagerHtml() ?>
    </div>
</div>
<?php endif ?>
