<?php
/**
 * BelVG
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 
 * @category   Belvg
 * @package    Chameleon Mobile Theme
 * @copyright  Copyright (c) 2010 - 2012 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <div class="box-title">
        <h2><?php echo $this->__('You May Also Like') ?></h2>
    </div>
    <ul class="products-grid" id="upsell-product-list"><!-
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            -><li class="item">
                <a href="<?php echo $_link->getProductUrl() ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(135) ?>" width="120" height="120" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>" /></a>
                <h3 class="product-name"><?php echo $this->escapeHtml($_link->getName()) ?></h3>
                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
            </li><!-
            <?php endif; ?>
        <?php endfor; ?>
    <?php endfor; ?>
    -></ul>
</div>
<?php endif ?>
