<?php 
$get_campaigns = Mage::helper('pushassist')->get_campaigns();
$check_api_key=Mage::app()->getStore()->getConfig('pushassistsection/general/apikey');
$check_secret_key=Mage::app()->getStore()->getConfig('pushassistsection/general/secretkey');
$account_response = Mage::helper('pushassist')->get_account_details();

if(isset($account_response['account_name'])){
$account_url='https://'.$account_response['account_name'].'.pushassist.com/dashboard/';
}
if($check_api_key!='' && $check_secret_key != '' && (!isset($account_response['error'] )) && $account_response ) {


?>
<div id="Psidebar" >
  <ul>
   <!-- <li><a href="<?php //echo $this->getUrl('*/pushassist_createaccount'); ?>">Create an Account</a></li>-->
    <li><a href="<?php echo $this->getUrl('*/pushassist_dashboard'); ?>"><?php echo $this->__('Dashboard')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationmain'); ?>"><?php echo $this->__('Notifications')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationsend'); ?>"><?php echo $this->__('Send Notification')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_segments'); ?>"><?php echo $this->__('Segments')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createsegments'); ?>"><?php echo $this->__('Create Segments')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_subscribers'); ?>"><?php echo $this->__('Subscribers')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_settings'); ?>"><?php echo $this->__('Settings')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_campaign'); ?>"><?php echo $this->__('Campaigns')?></a></li>
   </ul>
  </div>
 <?php echo $this->getLayout()->createBlock('core/html_calendar')->setTemplate('page/js/calendar.phtml')->toHtml();?>
<!-- Content Start -->
    <div id="pushassist" class="content dashboard clearfix">
        <!-- Start Page Header -->
        <div class="page-header">
            <h1 class="title"><?php echo $this->__('Campaigns');?></h1>
        </div>
        <!-- End Page Header -->

        <!-- Container Start -->
        <div class="container-widget clearfix">
           

            <!-- Project Stats Start -->
           
	      <?php if($account_response['planType']=='Free'){?>
	      <div class="col-md-6" style="width:54%">
		  <div class="panel panel-default">
			<div class="panel-body">
			  
			    <p><strong><?php echo $this->__('Campaigns');?></strong></p>
			    <p class="margin-b-20">	
			      <?php echo $this->__('Following screenshot shows how you can create and schedule a campaign.');?>
			      <strong><?php echo $this->__('This feature is available in premium plans.');?> </strong> </p>
			    <p class="align-center margin-b-25">
				  <a href="<?php echo $account_url;?>" target="_blank" class="btn btn-default margin-t-0"><?php echo $this->__('Upgrade to Premium');?></a>
			    </p>
			    <div class="margin-t-15 image_wrapper">
	
				<img src="<?php echo $this->getSkinUrl('pushassist/campaign.png') ?>" alt="Campaign Notification">
			    </div>

			</div>
		  </div>
		</div>
		<?php } ?>
		<?php if($account_response['planType']=='Paid'){ ?>
		<div class="col-md-6">
		  <div class="panel panel-default">
		  <div class="panel-body">
		    <form action="<?php echo $this->getUrl('*/*/createcampaign'); ?>" method="post" name="campaign" enctype='multipart/form-data' >
		    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
			 <div class="form-group">
                                <label class="col-sm-3 control-label form-label"><?php echo $this->__('Campaign Title')?></label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="title" name="title" placeholder="Campaign Title" maxlength="77" required="required" />
                                    <span class="pull-right"><?php echo $this->__('Limit 77 Characters')?></span>
                                </div>
                         </div>
			 <div class="form-group">
                                <label class="col-sm-3 control-label form-label"><?php echo $this->__('Campaign Message')?></label>
                                <div class="col-sm-9">
                                    <textarea class="form-control" rows="2" name="message" id="message" placeholder="Campaign Message" maxlength="138" required="required" style="resize: none"></textarea>
                                    <span class="pull-right"><?php echo $this->__('Limit 138 Characters')?></span>
                                </div>
                         </div>
                         <div class="form-group">
                                <label class="col-sm-3 control-label form-label"><?php echo $this->__('Campaign URL')?></label>
				<div class="col-sm-9 margin-b-15">
                                    <input type="url" maxlength="250" placeholder="Campaign URL" name="url" id="url" class="form-control" >
                                </div>
			 </div>
			<div class="form-group">
                                <label class="col-sm-3 control-label form-label">Campaign Date</label>

                                <div class="col-sm-9 input-group date" form_datetime id="form_datetime" data-date=""  data-link-field="date">
                                    <input  size="20" type="text" name="campaigndate" value="" id="campaigndate"/>
                                    
				   
		      <img title="Select date" id="cal_date_trig_campaign" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>"  class="v-middle" style="width:14px;height:14px;"/>  
                                </div>
                               
                          </div>
			  <div class="form-group margin-b-0">
                                <label for="focusedinput" class="col-sm-3 control-label form-label"><?php echo $this->__('Campaign Logo')?></label>    
                                <div class="col-sm-9">
                                    <span class="btn btn-success fileinput-button margin-b-10">
                                        <span><?php echo $this->__('Campaign Logo')?>...</span>
                                        <input id="fileupload" type="file" name="fileupload" />
                                    </span>
				    <span class="clearfix"><?php echo $this->__('Image size must be exactly 250x250px.')?></span>
                                    <!-- The global progress bar -->
                                    <div id="progress" class="progress">
                                        <div class="progress-bar progress-bar-success"></div>
                                    </div>
                                </div>
                            </div>
			    <div class="form-group">
                                <label class="col-sm-offset-3 control-label form-label">    
                                    <input type="checkbox" value="1" name="is_utm_show" id="is_utm_show" />
                                    <label class="form-label checkbox_title margin-l-10"><?php echo $this->__('Add UTM Parameters')?></label>    
                                </label>
                            </div>
			    <div class="form-group" id="utm_parameter_div" style="display: none;">    
                                <label class="col-sm-3 control-label form-label"><?php echo $this->__('UTM Source')?></label>
                                <div class="col-sm-9 margin-b-15">
                                    <input type="text" class="form-control" id="utm_source" name="utm_source" value="pushassist" placeholder="Enter UTM Source" maxlength="45" required="required" />
                                    <span class="pull-right"><?php echo $this->__('Limit 45 Characters')?></span>
                                </div>

                                <label class="col-sm-3 control-label form-label"><?php echo $this->__('UTM Medium')?></label>
                                <div class="col-sm-9 margin-b-15">
                                    <input type="text" class="form-control" name="utm_medium" id="utm_medium" value="pushassist_notification" placeholder="Enter UTM Medium" maxlength="73" required="required" />
                                    <span class="pull-right"><?php echo $this->__('Limit 73 Characters')?></span>
                                </div>

                                <label class="col-sm-3 control-label form-label"><?php echo $this->__('UTM Campaign')?></label>
                                <div class="col-sm-9 margin-b-15">
                                    <input type="text" class="form-control" name="utm_campaign" id="utm_campaign" value="pushassist" placeholder="Enter UTM Campaign" maxlength="500" required="required"  />
                                    <span class="pull-right"><?php echo $this->__('Limit 500 Characters')?></span>
                                </div>    
                              
                            </div>
			     <div class="form-group">
                                <label class="col-sm-3 control-label form-label"><?php echo $this->__('Segment')?></label>
                                <div class="col-sm-9 dropdown_padding">
                                    <select class="col-sm-12" id="segment" name="segment[]"  multiple>
				      <?php $get_segment = Mage::helper('pushassist')->get_segments(); 
					    if(count($get_segment) > 0){ 
						foreach($get_segment as $get_segment_list){
					    ?>
						<option value="<?php echo $get_segment_list['id'];?>"><?php echo $get_segment_list['name'];?></option>
					<?php  }  } else{ 
					?>
					<option value=""><?php echo $this->__('No Segment')?></option>
                                        <?php } ?>
                                        
                                    </select>
                                </div>
                            </div>
			    <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-1 col-xs-3">
                                    <button type="submit" class="btn btn-default"><?php echo $this->__('Schedule')?></button>
                                </div>
			    </div>
		    </form>
		  </div>
		  </div>
	      </div>
	      <div class="col-md-6 dummy-notification shadow panel panel-default">
			      <p class="h4 pb15">Preview</p>
			      <div class="widget shadow dummy-notification-inner-wrapper">
				  <div class="wrapper">
				      <div class="img_wrapper pull-left">
					  <img class="img-responsive" src="<?php echo $account_response['site_image'];?>" id="pushassist_preview_logo">
				      </div>
				      <div class="text_wrapper pull-left">
					  <div class="title">
					      <div id="notification_title" class="title_txt pull-left"><?php echo $this->__('Campaign Title')?></div>
					      <div class="closer pull-right">x</div>
					  </div>
					  <div id="notification_message" class="message"><?php echo $this->__('Campaign Body')?></div> 
					  <div class="domain">
						  <div class="domain"><?php echo $account_response['account_name'];?>.pushassist.com</div>
					  </div>
				      </div>
				  </div>
			      </div>
			      <div class="redirect_url">
					<p class="h5" id="redirect_url" name="redirect_url"><?php echo $this->__('URL to open when user clicks the notification')?>:</p>
			      </div>
		</div>
		  <script language="javascript">

			Calendar.setup({
				inputField : 'campaigndate',
				ifFormat : '%Y-%m-%e %H:%M:%S',
				button : 'cal_date_trig_campaign',
				align : 'Bl',
				singleClick : true
			    });
		jQuery.noConflict();
jQuery(document).ready(function() {
"use strict";
		 var $url = "";
			
		 jQuery("#title").keyup(function () {
		 
            title = jQuery('#title').val();

            if (title != "") {
                jQuery('#notification_title').text(title);
            }
            else {
                jQuery('#notification_title').text('<?php echo $this->__('Campaign Title')?>');
            }
        });

        jQuery("#message").keyup(function () {

             message = jQuery('#message').val();

            if (message != "") {
                jQuery('#notification_message').text(message);               
            }
            else {

                jQuery('#notification_message').text('<?php echo $this->__('Campaign Body')?>');                
            }
        });

        jQuery("#url,#utm_medium,#utm_source, #utm_campaign").keyup(function () {

            $url = jQuery('#url').val();

            if ($url != "" && jQuery('#is_utm_show').is(':checked')) {

                jQuery('#redirect_url').text($url + "?utm_source=" + jQuery('#utm_source').val() + "&utm_medium=" + jQuery('#utm_medium').val() + "&utm_campaign=" + jQuery('#utm_campaign').val());                

            } else if ($url != "") {
			
                jQuery('#redirect_url').text($url);                
            }
            else {
                jQuery('#redirect_url').text('<?php echo $this->__('URL to open when user clicks the notification')?>:');                
            }
        });

	

        jQuery("#title").blur(function () {
            title = jQuery('#title').val();

            if (title != "") {
                jQuery('#notification_title').text(title);
            }
            else {
                jQuery('#notification_title').text('<?php echo $this->__('Campaign Title')?>');
            }
        });

        jQuery("#message").blur(function () {
		
            message = jQuery('#message').val();

            if (message != "") {
                jQuery('#notification_message').text(message);               
            }
            else {

                jQuery('#notification_message').text('<?php echo $this->__('Campaign Body')?>');                
            }
        });

        jQuery("#url").blur(function () {

            $url = jQuery('#url').val();

            if ($url != "" && jQuery('#is_utm_show').is(':checked')) {

                jQuery('#redirect_url').text($url + "?utm_source=" + jQuery('#utm_source').val() + "&utm_medium=" + jQuery('#utm_medium').val() + "&utm_campaign=" + jQuery('#utm_campaign').val());                

            } else if ($url != "") {
			
                jQuery('#redirect_url').text($url);                
            }
            else {
                jQuery('#redirect_url').text('<?php echo $this->__('URL to open when user clicks the notification')?>:');                
            }
        });
		
		jQuery("#is_utm_show").on('click', function () {
		
			if (jQuery('#is_utm_show').is(':checked')) { 


					jQuery('#utm_parameter_div').show('slow');

					if ($url == "") {

						jQuery('#redirect_url').text('<?php echo $this->__('URL to open when user clicks the notification')?>:');
					} else {

						jQuery('#redirect_url').text($url + "?utm_source=" + jQuery('#utm_source').val() + "&utm_medium=" + jQuery('#utm_medium').val() + "&utm_campaign=" + jQuery('#utm_campaign').val());
					}

				} else {

					jQuery('#utm_parameter_div').hide('slow');

					if ($url == "") {

						jQuery('#redirect_url').text('<?php echo $this->__('URL to open when user clicks the notification')?>:');
					} else {

						jQuery('#redirect_url').text($url);
					}
				}
		});
	});	
	</script>   
		<?php } ?>
            
            <!-- Project Stats End -->
        </div>
        <!-- Container End -->
    </div>
    <!-- Content End -->
<?php
}else{
 Mage::app()->getResponse()->setRedirect(Mage::helper("adminhtml")->getUrl("adminhtml/pushassist_createaccount/index/"));
} ?>
