<?php 
$get_notifications = Mage::helper('pushassist')->get_notifications();

$check_api_key=Mage::app()->getStore()->getConfig('pushassistsection/general/apikey');
$check_secret_key=Mage::app()->getStore()->getConfig('pushassistsection/general/secretkey');
$account_response = Mage::helper('pushassist')->get_account_details();
if(isset($account_response['account_name'])){
$account_url='https://'.$account_response['account_name'].'.pushassist.com/dashboard/';
}

if($check_api_key!='' && $check_secret_key != '') {

?>
<div id="Psidebar" >
  <ul>
    <li><a href="<?php echo $this->getUrl('*/pushassist_dashboard'); ?>"><?php echo $this->__('Dashboard')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationmain'); ?>"><?php echo $this->__('Notifications')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationsend'); ?>"><?php echo $this->__('Send Notification')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_segments'); ?>"><?php echo $this->__('Segments')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createsegments'); ?>"><?php echo $this->__('Create Segments')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_subscribers'); ?>"><?php echo $this->__('Subscribers')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_settings'); ?>"><?php echo $this->__('Settings')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_campaign'); ?>"><?php echo $this->__('Campaigns')?></a></li>
  </ul>
  </div>
<!-- Content Start -->
    <div id="pushassist" class="content dashboard clearfix">
        <!-- Start Page Header -->
        <div class="page-header">
            <h1 class="title"><?php echo $this->__('Sent Notifications')?></h1>
	    <div class="sub_count">
		<a href="<?php echo $this->getUrl('*/pushassist_notificationsend'); ?>"><?php echo $this->__('Send New Notification')?></a>
	    </div>
        </div>
        <!-- End Page Header -->

        <!-- Container Start -->
        <div class="container-widget clearfix">
           

            <!-- Project Stats Start -->
            <div class="col-md-12 col-lg-12">
                <div class="panel panel-widget">
		  <?php if( count($get_notifications) > 0){ ?>
                   
                    <div class="panel-body table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <td>#</td>
                                <td><?php echo $this->__('Site Url')?></td>                               
				<td><?php echo $this->__('Message')?></td>
				<td><?php echo $this->__('Total Sent')?></td>
				<td><?php echo $this->__('Delivered')?></td>
				<td><?php echo $this->__('Unsubscribed')?></td>
				<td><?php echo $this->__('Clicked')?></td>
				<td><?php echo $this->__('Created Date')?></td>
                            </tr>
                            </thead>
                            <tbody>
			      <?php $i = 1;
				foreach($get_notifications as $get_notifications_list){
				$clicked_percentage=@($get_notifications_list['total_clicked']/$get_notifications_list['total_sent'])*100;
				?>
                                <tr>
				
                                    <td><?php echo $i;?></td>
                                    <td><?php echo $get_notifications_list['siteurl']?></td>                                   
				    <td class="message">
					<div class="col-sm-3 table_image">
						<img src="<?php echo $get_notifications_list['logo']?>" alt="Notification Logo">
					</div>

					<div class="col-sm-8">
					    <h5 class="margin-t-0 font-bold">
						
						  <?php echo  $get_notifications_list['title'];?>
					    </h5>
					    <p class="margin-b-5"><?php echo  $get_notifications_list['message'];?></p>
					    <a target="_blank" href="<?php echo $get_notifications_list['redirecturl'];?>"><?php echo $get_notifications_list['redirecturl'];?></a>
					</div>
				    </td>
				    
				    <td><?php echo $get_notifications_list['total_sent']+$get_notifications_list['failed'];?></td>
				    <td><?php echo $get_notifications_list['total_sent']?></td>
                                    <td><?php echo $get_notifications_list['failed'];?></td>
				    <td><?php echo $get_notifications_list['total_clicked'];?> 
					<?php if($clicked_percentage>0){
					?>	
					  <b class="color-up margin-l-10"> <?php echo (int)$clicked_percentage; } else { ?> <b class="color-up margin-l-10">0 <?php } ?> %</b>
				    </td>
				    
				    <td><?php echo date("M d, Y H:i:s",strtotime($get_notifications_list['created_at']));?></td>
                                </tr>
				  
                                <?php $i++;
				  } ?>
                                                              
                            </tbody>
                        </table>
                    </div>
		    <?php }else{ echo $this->__('No result found');}?>
                </div>
            </div>
            <!-- Project Stats End -->

        </div>
        <!-- Container End -->

    </div>
    <!-- Content End -->
<?php 
}else{

Mage::app()->getResponse()->setRedirect(Mage::helper("adminhtml")->getUrl("adminhtml/pushassist_createaccount/index/"));
}
?>