<?php $get_subscribers = Mage::helper('pushassist')->get_subscribers();
$check_api_key=Mage::app()->getStore()->getConfig('pushassistsection/general/apikey');
$check_secret_key=Mage::app()->getStore()->getConfig('pushassistsection/general/secretkey');
$account_response = Mage::helper('pushassist')->get_account_details();
if(isset($account_response['account_name'])){
$account_url='https://'.$account_response['account_name'].'.pushassist.com/dashboard/';
}
if($check_api_key!='' && $check_secret_key != '' && (!isset($account_response['error'] )) && $account_response ) {
if( count($get_subscribers) > 0){ 
//print_r($get_segement);
?>
<div id="Psidebar" >
   <ul>
    <li><a href="<?php echo $this->getUrl('*/pushassist_dashboard'); ?>"><?php echo $this->__('Dashboard')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationmain'); ?>"><?php echo $this->__('Notifications')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationsend'); ?>"><?php echo $this->__('Send Notification')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_segments'); ?>"><?php echo $this->__('Segments')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createsegments'); ?>"><?php echo $this->__('Create Segments')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_subscribers'); ?>"><?php echo $this->__('Subscribers')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_settings'); ?>"><?php echo $this->__('Settings')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_campaign'); ?>"><?php echo $this->__('Campaigns')?></a></li>
   </ul>
  </div>
<!-- Content Start -->
    <div id="pushassist" class="content dashboard clearfix">
        <!-- Start Page Header -->
        <div class="page-header">
            <h1 class="title"><?php echo $this->__('Subscribers Details')?></h1>
        </div>
        <!-- End Page Header -->

        <!-- Container Start -->
        <div class="container-widget clearfix">
           

            <!-- Project Stats Start -->
            <div class="col-md-12 col-lg-12">
                <div class="panel panel-widget">
                  
                    <div class="panel-search">
                        <form>
                            <input type="text" class="form-control" placeholder="Search...">
                            <i class="fa fa-search icon"></i>
                        </form>
                    </div>
                    <div class="panel-body table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <td>#</td>
                                <td><?php echo $this->__('Site Url')?></td>
                                <td><?php echo $this->__('Chrome')?></td>
				<td><?php echo $this->__('Firefox')?></td>
				<td><?php echo $this->__('Safari')?></td>
                            </tr>
                            </thead>
                            <tbody>
			      <?php $i = 1;
				foreach($get_subscribers as $get_subscribers_list){?>
                                <tr>
				
                                    <td><?php echo $i;?></td>
                                    <td><?php echo $get_subscribers_list['siteurl']?></td>
                                    <td><?php echo $get_subscribers_list['Chrome'];?></td>
				    <td><?php echo $get_subscribers_list['Firefox'];?></td>
				    <td><?php echo $get_subscribers_list['Safari'];?></td>
                                </tr>
				  
                                <?php $i++;
				  } ?>
                                                              
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Project Stats End -->
        </div>
        <!-- Container End -->
    </div>
    <!-- Content End -->
<?php }else{ 
	    echo $this->__('No result found');
} 
}else{
Mage::app()->getResponse()->setRedirect(Mage::helper("adminhtml")->getUrl("adminhtml/pushassist_createaccount/index/"));
}
?>