
             <?php if($crumbs && is_array($crumbs)): ?>
                <div class="breadcrumbs">
                    <div class="a-left">
<?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
                    <div class="<?php echo $_crumbName ?> ">
                         <?php if($_crumbInfo['link']): ?>
                            <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
                                        <?php elseif($_crumbInfo['last']): ?>
                <strong><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
            <?php else: ?>
                            <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
            <?php endif; ?>
                           <?php if(!$_crumbInfo['last']): ?>
                <i class="fa fa-fw fa-angle-right c68"></i>
            <?php endif; ?>            
                        </div>

   <?php endforeach; ?>
                     </div>
                </div>

<?php endif; ?>