<?php 
	// Name id
	$productList_1 = $this->getCategoryProduct(5);
	$productList_2 = $this->getCategoryProduct(10);
	$productList_3 = $this->getCategoryProduct(17);
	$productList_4 = $this->getCategoryProduct(19);

    $_helper = $this->helper('catalog/output');
 ?>
<!-- Table Switch -->
<div class="home-table-products">
		<div class="global-container">
			<div class="menu-all-pages-container">
			<div class="tableBox" id="alllink">
					<div class="hd">
						<ul class="bableBox-header ">
							<li class="on"><a href="javascript:;">Engagement Rings</a></li>
							<li class=""><a href="javascript:;">Promise Rings</a></li>
							<li class=""><a href="javascript:;">Birthstone Rings</a></li>
							<li class=""><a href="javascript:;">Skull Rings</a></li>
						</ul>
					</div>
					<div class="bd">
						<ul>
<?php 
// echo $productList_1->count();
if($productList_1->count()): ?>
	  <?php  
	  $p1 = 0;
	  foreach ($productList_1 as $_product): ?>
	  		<?php 
	  		$p1++;
	  	
	  		if($p1 <= 4){?>
						<!-- Product S -->
							<li >
								<div class="item-content">
                                    <!-- Off -->
                                    <?php
                                        if($_product->getIsoff()){
                                         $old_price = $_product->getPrice();  ?>
                                    <?php $special_price = $_product->getFinalPrice();?>
                                    <?php $percent = ceil((($old_price-$special_price)/$old_price)*100)?>
                                    <?php if($percent){?>
                                                        <div class="deal-content">
                                                                <div class="flash-sale-offtag"><?php echo $percent ?>% OFF</div>
                                                        </div>                 
                                    <?php }} ?>     									
									<div class="product-image-area">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                     <a target="_blank" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" rel="nofollow" >   <span  class="addtowishlist"></span></a>
                                        <?php endif; ?>

										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" 
                                            <?php $_imgSize = 280; ?>>
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                        </a>

									</div>
									<div class="details-area">

										<div class="hoverBox">
											<?php if($_product->getRatingSummary()): ?>
											<!-- Rating -->
											<div class="ratings-fa-star">			
						                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
						                    </div>
 											<?php endif; ?>

											<!-- Name -->
											<div class="product-name">
												 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
											</div>
										</div>

											<!-- Price -->
										<div class="price-box">
											<?php echo $this->getPriceHtml($_product, true) ?>
										</div>
									

                                       <!-- Label -->
                                        <div class="clear"></div>
                                        <div class="product-free">
                                            <div class="product-label product-label-label">

<?php 
/**  Get Product Attribute Value S  **/
$product_id = $_product->getId();
$table_name = 'catalog_product_entity_varchar';
$codeId = 162 ;

// Product Attribute Value
$getAttributeCollection = $this->getAttribute($codeId, $table_name,$product_id);

// Product Attribute Name
$attributes = $this->getAttributeValue($getAttributeCollection);

/**  Get Product Attribute Value E  **/
?>                                                <?php 
foreach ($attributes as $k => $v) {
     if($v) {
                                                   ?>
                                                    <span class="product-label-icon label-color_<?php echo $k; ?>"><?php echo $v; ?></span>
                                                   <?php
                                                }} ?>
                                            </div>
									</div>
								</div>
							</li>
							<!-- Product E -->
				<?php } ?>
	  <?php endforeach; ?>
 <?php endif; ?>
						</ul>
						<ul>

<?php 
// echo $productList_1->count();

if($productList_2->count()): ?>
	  <?php  
	  $p2 = 0;
	  foreach ($productList_2 as $_product): ?>
	  		<?php 
	  		$p2++;
	  	
	  		if($p2 <= 4){?>
						<!-- Product S -->
							<li >
								<div class="item-content">
                                    <!-- Off -->
                                    <?php
                                        if($_product->getIsoff()){
                                         $old_price = $_product->getPrice();  ?>
                                    <?php $special_price = $_product->getFinalPrice();?>
                                    <?php $percent = ceil((($old_price-$special_price)/$old_price)*100)?>
                                    <?php if($percent){?>
                                                        <div class="deal-content">
                                                                <div class="flash-sale-offtag"><?php echo $percent ?>% OFF</div>
                                                        </div>                 
                                    <?php }} ?>     

									<div class="product-image-area">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                     <a target="_blank" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" rel="nofollow" >   <span  class="addtowishlist"></span></a>
                                        <?php endif; ?>

										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" 
                                            <?php $_imgSize = 280; ?>>
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                        </a>

									</div>
									<div class="details-area">

										<div class="hoverBox">
											<?php if($_product->getRatingSummary()): ?>
											<!-- Rating -->
											<div class="ratings-fa-star">			
						                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
						                    </div>
 											<?php endif; ?>
 											
											<!-- Name -->
											<div class="product-name">
												 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
											</div>
										</div>

											<!-- Price -->
										<div class="price-box">
											<?php echo $this->getPriceHtml($_product, true) ?>
										</div>
									

                                       <!-- Label -->
                                        <div class="clear"></div>
                                        <div class="product-free">
                                            <div class="product-label product-label-label">
<?php 
/**  Get Product Attribute Value  S  **/
$product_id = $_product->getId();
$table_name = 'catalog_product_entity_varchar';
$codeId = 162 ;

// Product Attribute Value
$getAttributeCollection = $this->getAttribute($codeId, $table_name,$product_id);

// Product Attribute Name
$attributes = $this->getAttributeValue($getAttributeCollection);

/**  Get Product Attribute Value E  **/
?>                                                <?php 
foreach ($attributes as $k => $v) {
     if($v) {
                                                   ?>
                                                    <span class="product-label-icon label-color_<?php echo $k; ?>"><?php echo $v; ?></span>
                                                   <?php
                                                }} ?>
                                            </div>	



									</div>
								</div>
							</li>
							<!-- Product E -->
				<?php } ?>
	  <?php endforeach; ?>
 <?php endif; ?>					

						</ul>
						<ul>
<?php 
// echo $productList_1->count();

if($productList_3->count()): ?>
	  <?php  
	  $p3 = 0;
	  foreach ($productList_3 as $_product): ?>
	  		<?php 
	  		$p3++;
	  	
	  		if($p3 <= 4){?>
						<!-- Product S -->
							<li >
								<div class="item-content">
                                    <!-- Off -->
                                    <?php
                                        if($_product->getIsoff()){
                                         $old_price = $_product->getPrice();  ?>
                                    <?php $special_price = $_product->getFinalPrice();?>
                                    <?php $percent = ceil((($old_price-$special_price)/$old_price)*100)?>
                                    <?php if($percent){?>
                                                        <div class="deal-content">
                                                                <div class="flash-sale-offtag"><?php echo $percent ?>% OFF</div>
                                                        </div>                 
                                    <?php }} ?>     									
									<div class="product-image-area">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                     <a target="_blank" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" rel="nofollow" >   <span  class="addtowishlist"></span></a>
                                        <?php endif; ?>

										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" 
                                            <?php $_imgSize = 280; ?>>
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                        </a>

									</div>
									<div class="details-area">

										<div class="hoverBox">
											<?php if($_product->getRatingSummary()): ?>
											<!-- Rating -->
											<div class="ratings-fa-star">			
						                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
						                    </div>
 											<?php endif; ?>

											<!-- Name -->
											<div class="product-name">
												 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
											</div>
										</div>

											<!-- Price -->
										<div class="price-box">
											<?php echo $this->getPriceHtml($_product, true) ?>
										</div>
									

                                       <!-- Label -->
                                        <div class="clear"></div>
                                        <div class="product-free">
                                            <div class="product-label product-label-label">

<?php 
/**  Get Product Attribute Value  S  **/
$product_id = $_product->getId();
$table_name = 'catalog_product_entity_varchar';
$codeId = 162 ;

// Product Attribute Value
$getAttributeCollection = $this->getAttribute($codeId, $table_name,$product_id);

// Product Attribute Name
$attributes = $this->getAttributeValue($getAttributeCollection);

/**  Get Product Attribute Value E  **/
?>                                                <?php 
foreach ($attributes as $k => $v) {
     if($v) {
                                                   ?>
                                                    <span class="product-label-icon label-color_<?php echo $k; ?>"><?php echo $v; ?></span>
                                                   <?php
                                                }} ?>
                                            </div>



									</div>
								</div>
							</li>
							<!-- Product E -->
				<?php } ?>
	  <?php endforeach; ?>
 <?php endif; ?>
						</ul>
						<ul>

<?php 
// echo $productList_1->count();

if($productList_4->count()): ?>
	  <?php  
	  $p4 = 0;
	  foreach ($productList_4 as $_product): ?>
	  		<?php 
	  		$p4++;
	  	
	  		if($p4 <= 4){?>
						<!-- Product S -->
							<li >
								<div class="item-content">
                                    <!-- Off -->
                                    <?php
                                        if($_product->getIsoff()){
                                         $old_price = $_product->getPrice();  ?>
                                    <?php $special_price = $_product->getFinalPrice();?>
                                    <?php $percent = ceil((($old_price-$special_price)/$old_price)*100)?>
                                    <?php if($percent){?>
                                                        <div class="deal-content">
                                                                <div class="flash-sale-offtag"><?php echo $percent ?>% OFF</div>
                                                        </div>                 
                                    <?php }} ?>     									
									<div class="product-image-area">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                     <a target="_blank" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" rel="nofollow" >   <span  class="addtowishlist"></span></a>
                                        <?php endif; ?>

										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" 
                                            <?php $_imgSize = 280; ?>>
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                        </a>

									</div>
									<div class="details-area">

										<div class="hoverBox">
											<?php if($_product->getRatingSummary()): ?>
											<!-- Rating -->
											<div class="ratings-fa-star">			
						                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
						                    </div>
 											<?php endif; ?>

											<!-- Name -->
											<div class="product-name">
												 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
											</div>
										</div>

											<!-- Price -->
										<div class="price-box">
											<?php echo $this->getPriceHtml($_product, true) ?>
										</div>
									

                                       <!-- Label -->
                                        <div class="clear"></div>
                                        <div class="product-free">
                                            <div class="product-label product-label-label">

<?php 
/**  Get Product Attribute Value  S  **/
$product_id = $_product->getId();
$table_name = 'catalog_product_entity_varchar';
$codeId = 162 ;

// Product Attribute Value
$getAttributeCollection = $this->getAttribute($codeId, $table_name,$product_id);

// Product Attribute Name
$attributes = $this->getAttributeValue($getAttributeCollection);

/**  Get Product Attribute Value E  **/
?>                                                <?php 
foreach ($attributes as $k => $v) {
     if($v) {
                                                   ?>
                                                    <span class="product-label-icon label-color_<?php echo $k; ?>"><?php echo $v; ?></span>
                                                   <?php
                                                }} ?>
                                            </div>
									</div>
								</div>
							</li>
							<!-- Product E -->
				<?php } ?>
	  <?php endforeach; ?>
 <?php endif; ?>				
						</ul>
					</div>
				</div>			
			</div>
		</div>
</div>
<script>
	jQuery(function(){
		jQuery(".tableBox").slide({effect:"left",trigger:"click"});
	});
</script>