<?php 
$_collections = $this->getCatalogRecommendProductCollenction();
if($_collections):
 ?>
<div class="swiper-container border-gradient thumbs-cotnainer swiper-container1">
 	<div class="box-title">
        <h2><?php echo $this->__('You May Also Like') ?></h2>
    </div>
    <div class="swiper-wrapper" id="upsell-product-list">
    <?php  foreach ($_collections as $_product): ?>
    <?php   if(!$_product->getId())continue;    ?>
            <div class="swiper-slide">
                <a href="<?php echo $_product->getProductUrl(); ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(90,120) ?>" width="90" height="120" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" /></a>
                <?php echo $this->getPriceHtml($_product, true, '-upsell') ?>
            </div>
    <?php  endforeach; ?>
   </div>
</div>
<?php endif ?>
<script type="text/javascript">
jQuery(function($){
	$('.swiper-container1').each(function(){
		$(this).swiper({
			initialSlide:2,
			slidesPerView:'auto',
			offsetPxBefore:0,
			offsetPxAfter:10,
			calculateHeight: true
		})	
	})
});
</script>