<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php if($this->getCollection()->getSize()): ?>

    <?php if($this->getUseContainer()): ?>
    <div class="pager">
    <?php endif ?>

    <?php if(false): //$this->getShowAmounts()): ?>
    <p class="amount">
        <?php if($this->getLastPageNum()>1): ?>
            <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
        <?php else: ?>
            <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
        <?php endif; ?>
    </p>
    <?php endif ?>

    <?php if(false): //$this->getShowPerPage()): ?>
    <div class="limiter">
        <label><?php echo $this->__('Show') ?></label>
        <select onchange="setLocation(this.value)">
        <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                <?php echo $_limit ?>
            </option>
        <?php endforeach; ?>
        </select> <?php echo $this->__('per page') ?>
    </div>
    <?php endif ?>

    <?php if($this->getLastPageNum()>1): ?>
    <div class="pages">
        <ul onchange="return false;setLocation(this.value)">
		    <?php if (!$this->isFirstPage()): ?>
			<li>
				<a class="prev-page can-open fancybox.ajax" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Prev') ?>">&#8592;&nbsp;<?php echo $this->__('Prev') ?></a>
			</li>
			<?php else: ?>
			<li><span class="prev-page disabled">&#8592;&nbsp;<?php echo $this->__('Prev') ?></span></li>
			<?php endif;?>
			
            <?php if ($this->canShowFirst()): ?>
                <li><a class="can-open fancybox.ajax" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
            <?php endif;?>

            <?php if ($this->canShowPreviousJump()): ?>
                <li value="<?php echo $this->getPreviousJumpUrl() ?>">...</li>
            <?php endif;?>

            <?php foreach ($this->getFramePages() as $_page): ?>
                <?php if ($this->isPageCurrent($_page)): ?>
                   <li class="current" selected="selected"><span><?php echo $_page ?></span></li>
                <?php else: ?>
                    <li><a class="can-open fancybox.ajax" href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($this->canShowNextJump()): ?>
                <li value="<?php echo $this->getNextJumpUrl() ?>">...</li>
            <?php endif;?>

            <?php if ($this->canShowLast()): ?>
                <li value="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></li>
            <?php endif;?>
       
        <?php if (!$this->isLastPage()): ?>
              <li>
				<a class="next-page can-open fancybox.ajax" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>"><?php echo $this->__('Next') ?>&nbsp;&#8594;</a>
			</li>
        <?php else: ?>
                <li><span class="next-page disabled"><?php echo $this->__('Next') ?>&nbsp;&#8594;</span></li>
        <?php endif;?>
		 </ul>
    </div>
    <?php endif; ?>

    <?php if($this->getUseContainer()): ?>
    </div>
    <?php endif ?>

<?php endif ?>