<?php
/**
 * Highslide product-magnifier extension for Magento
 * Copyright (c) 2009 Silverthemes.com (http://www.magentoshine.com)
 * Visit www.highslide.com for more information about Highslide
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<?php else: ?>
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(365).'" alt="'.$this->htmlEscape($_product->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image')
    ?>
<?php endif; ?>
<?php if (count($this->getGalleryImages()) > 0): ?>
    <div class="gallery-detail">
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?> 
        <li>
             <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(600,800); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" width="501" height="668"/>      
			         
       </li>
    <?php endforeach; ?>  
    </ul>
</div>
<?php endif; ?>
