<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017-10-14
 * Time: 9:41
 *  by@ado
 *  格式抄自 shein.com
 */
?>
<div class="fl pj-new-con pj-new-comment caluted-pos-left caluted-pos">
    <span class="ic ic-info ic-pull-left"></span>
    <div class="bubblemenu comment-attr" >
	    <div class="top-arrow">
        <em  class="sanjiao_down"></em>
		</div>
        <div class="comment-attr-tb">
            <div class="comment-info">
                <div class="comment-img">
                    <div class="comment-img-right">
                        <?php echo $this->getReviewSummaryHtml(); ?>
                      </div>
                </div>

                <?php if($review = $this->getLastReview()): ?>
                <div class="comment-exm">
                                    <span class="comment-by">
                    <?php if($review->getNickname()): ?>  <?php echo $this->__('By'); ?> &nbsp;<em><?php echo $review->getNickname(); ?></em> <?php endif; ?>
                                    </span>
                    <p class="top-coment-ctn coment-content coment-content-defult">
                       <?php echo $review->getDetail(); ?>
                    </p>
                </div>
                <a class="she-btn-black she-btn-s" href="<?php echo $this->getProduct()->getProductUrl();?>#customer-reviews" target="_blank"><?php echo $this->__('See All Reviews') ?></a>
                <?php endif; ?>
            </div>

            <?php  $attributes = $this->getAdditionalData(); ?>
            <?php if(!empty($attributes)): ?>
            <div class="seo-attr">
                <?php foreach ($attributes as $item): ?>
                <div class="seo-attr-tr">
                    <div class="seo-attr-name"><?php echo $item['label'];?></div>
                    <div class="seo-attr-value"><?php echo $item['value'];?></div>
                </div>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>