<?php
/**
 * BelVG
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 
 * @category   Belvg
 * @package    Chameleon Mobile Theme
 * @copyright  Copyright (c) 2010 - 2012 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-img-mobile')->toHtml() ?>
<?php if($_menu): ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('flash-sale-mobile')->toHtml() ?>
<div class="nav-wrap">
    <div id="nav-container">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-link-mobile')->toHtml() ?>
    </div>
</div>
<?php endif ?>
