<?php
/**
 * BelVG
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 
 * @category   Belvg
 * @package    Chameleon Mobile Theme
 * @copyright  Copyright (c) 2010 - 2012 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('My Product Reviews') ?></h1>
</div>
<div class="review-history">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if( $this->getCollection() && $this->count()): ?>
        <?php echo $this->getToolbarHtml() ?>
            <ol class="list">
                <?php foreach ($this->getCollection() as $_review): ?>
                <li class="list-item">
                    <dl>
                        <dt>
                            <h2 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->escapeHtml($_review->getName()) ?></a></h2>
                            <span class="date">(<?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?>)</span>
                        </dt>
                        <?php if($_review->getSum()): ?>
                            <dd>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                                </div>
                            </dd>
                        <?php endif; ?>
                        <dd><?php echo $this->helper('review')->getDetailHtml($_review->getDetail()) ?></dd>
                        <dd><a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>"><?php echo $this->__('View Details') ?></a></dd>
                    </dl>
                </li>
                <?php endforeach; ?>
            </ol>
    <?php else: ?>
        <p><?php echo $this->__('You have submitted no reviews.') ?></p>
    <?php endif; ?>
</div>
