<?php
/**
 * BelVG
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 
 * @category   Belvg
 * @package    Chameleon Mobile Theme
 * @copyright  Copyright (c) 2010 - 2012 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
?>
<?php if( $this->getCollection() && $this->count()): ?>
<div class="box-account box-reviews">
    <div class="box-head">
        <h2><?php echo $this->__('My Recent Reviews') ?> <span class="separator">|</span>
        <a href="<?php echo $this->getAllReviewsUrl() ?>"><?php echo $this->__('View All Reviews') ?></a></h2>
    </div>
    <ol id="my_recent_reviews">
    <?php $iterator = 0 ?>
    <?php foreach ($this->getCollection() as $_review): ?>
        <li class="item">
            <span class="number"><strong><?php echo ++$iterator ?></strong>.</span>
            <div class="details">
                <h3 class="product-name"><a href="<?php echo $this->getReviewUrl($_review->getReviewId()) ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></h3>
                <?php if($_review->getSum()): ?>
                    <div class="ratings">
                        <strong><?php echo $this->__('Rating:') ?></strong>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('my_recent_reviews');</script>
</div>
<?php endif; ?>