<?php
if($this->helper->mobileShippingFirst()): //new billing last start
?>
<div class="easy-step" id="easycheckout-addressbilling" <?php if(false): // if($this->someAsShipping()): ?> style="display:none;" <?php endif;?>>
	<h2 class="ter"><?php echo $this->__('Billing Address')?>:</h2>
	
	<ul class="form-list address-form-list" <?php if(!$this->isThreeColsMode()):?>id="billing-address-form"<?php endif;?>>
		
		<?php if ($this->customerHasAddresses()): ?>
        <li>
            <label style="text-align:left;width:auto;float:none;" for="billing-address-select"><?php echo $this->__('Select a billing address from your address book.') ?></label>
            <div>
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
    	<?php endif; ?>
		
	    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?> >
	        <fieldset>
	            <ul <?php if(!$this->isThreeColsMode()):?> class="left" <?php endif;?>>
					<li>
		
						<div class="field name-firstname">
					        <label for="billing:firstname" class="required ehd"><em>*</em><?php echo $this->__('First Name:') ?></label>
					        <div class="input-box">
					            <input type="text" id="billing:firstname" name="billing[firstname]" value="<?php echo $this->getAddress()->getFirstname(); ?>" title="<?php echo $this->__('First Name') ?>" placeholder="<?php echo $this->__('First Name:') ?>"  autocomplete="given-name" class="input-text required-entry" />
					        </div>
                            
					    </div>
                        <div class="field name-lastname">
                        	<label for="billing:lastname" class="required ehd"><em>*</em><?php echo $this->__('Last Name:') ?></label>
					        <div class="input-box">
					            <input type="text" id="billing:lastname" name="billing[lastname]" value="<?php echo $this->getAddress()->getLastname(); ?>" title="<?php echo $this->__('Last Name') ?>" placeholder="<?php echo $this->__('Last Name:') ?>"  autocomplete="family-name" class="input-text required-entry" />
					        </div>
                            
					    </div>
					    
					</li>
					
						<?php if(!$this->isCustomerLoggedIn()): ?>
				        <li>
	                    <div class="field">
	                        <label for="billing:email" class="required ehd"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                        <div class="input-box">
	                            <input type="email" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>" autocomplete="email" class="input-text validate-email required-entry" />
	                        </div>
	                    </div>
	                    </li>
	                    <?php else:?>
	                    <li>
	                    <div class="field">
	                        <label class="required ehd"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                        <div class="input-box">
	                            <input type="email" name="billing[email]" readonly="readonly" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>" class="input-text readonly" />
	                        </div>
	                    </div>
	                    </li>
			        	<?php endif ?>
					  
                     <li>
						
						<div class="field">
		                    <label for="billing:street1" class="required ehd"><em>*</em><?php echo $this->__('Street line') ?> 1</label>
		                    <div class="input-box">
		                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" placeholder="<?php echo $this->__('Street line') ?> 1" autocomplete="address-line1" class="input-text required-entry" />
		                    </div>
                           
		                </div>
					
					</li>
					<li>
						
						<div class="field">
		                	<label for="billing:street2" class="ehd"><?php echo $this->__('Street line') ?> 2</label>
		                    <div class="input-box">
		                        <input type="text" title="<?php echo $this->__('Street Address %s', 2) ?>" name="billing[street][]" id="billing:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" placeholder="<?php echo $this->__('Street line') ?> 2" autocomplete="address-line2" class="input-text" />
		                    </div>
                             
		                </div>
						
					</li> 
                    
                    <li>
						
						<div class="field">
	                        <label for="billing:city" class="required ehd"><em>*</em><?php echo $this->__('City') ?></label>
	                        <div class="input-box">
	                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" placeholder="<?php echo $this->__('City') ?>" autocomplete="address-level1" class="input-text required-entry" id="billing:city" />
	                        </div>
	                    </div>
						
					</li>    
                        
					<li>
						
						<div class="field">
	                        <label for="billing:country_id" class="required ehd"><em>*</em><?php echo $this->__('Country') ?></label>
	                        <div class="input-box">
	                            <?php echo $this->getCountryHtmlSelect('billing') ?>
	                        </div>
	                    </div>
						
					</li>
					
					<li>
						
						<div class="field">
	                        <label for="billing:region_id" class="required ehd"><em>*</em><?php echo $this->__('State/Province') ?></label>
	                        <div class="input-box">
	                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
	                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
	                            </select>
	                            <script type="text/javascript">
	                            //<![CDATA[
	                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
	                            //]]>
	                            </script>
	                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" placeholder="<?php echo $this->__('State/Province') ?>" autocomplete="address-level2" class="input-text" style="display:none;" />
	                        </div>
	                    </div>
						
					</li>
					
					<li>
						
						<div class="field">
	                        <label for="billing:postcode" class="required ehd"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
	                        <div class="input-box">
	                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" placeholder="<?php echo $this->__('Zip/Postal Code') ?>" autocomplete="postal-code" class="input-text required-entry" />
	                        </div>
	                    </div>
						
					</li>
					
					<li>
						
						<div class="field">
	                        <label for="billing:telephone" class="required ehd"><em>*</em><?php echo $this->__('Telephone') ?></label>
	                        <div class="input-box">
	                            <input type="text" name="billing[telephone]" value="<?php $_tel = $this->getAddress()->getTelephone();
								 $_tel =($_tel)?$_tel:Mage::getSingleton('checkout/session')->getBillingTelephone();
								echo  $this->htmlEscape($_tel);
								 ?>" title="<?php echo $this->__('Telephone') ?>" placeholder="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="billing:telephone" />
	                        </div>
                            
                            
	                    </div>
						
					</li>
					
                    <?php if($this->helper->faxcompanyEnabled()): ?>
					<li>
					
						<div class="field">
	                        <label for="billing:fax" class="ehd"><?php echo $this->__('Fax') ?></label>
	                        <div class="input-box">
	                            <input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" placeholder="<?php echo $this->__('Fax') ?>" class="input-text" id="billing:fax" />
	                        </div>
	                    </div>
						
					</li>
						
					<li>
						
						<div class="field">
	                        <label for="billing:company" class="ehd"><?php echo $this->__('Company') ?></label>
	                        <div class="input-box">
	                            <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" placeholder="<?php echo $this->__('Company') ?>" class="input-text" />
	                        </div>
	                    </div>
						
					</li>
                    <?php endif; ?>
                </ul>
	        </fieldset>
	    </li>
	    <?php if($this->isThreeColsMode() && $this->getLayout()->getBlock('checkout.onepage.address.billing')->canShow()): ?>
			<li>
			 	<label style="width:auto" for="billing_use_for_shipping_yes"><input class="radio" type="checkbox" name="billing[use_for_shipping]" id="billing_use_for_shipping_yes" value="1" <?php if($this->getLayout()->getBlock('checkout.onepage.address.shipping')->someAsBilling()):?> checked="checked" <?php endif;?> class="radio" /><?php echo $this->__('Ship to the same address');?></label>
				
			</li>
		
		<?php endif;?>



	 </ul>
	
	<script type="text/javascript">
	//<![CDATA[
	    
	    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
	    
	//]]>
	</script>
</div>
<?php else: // old bliiing start =================================================================//  ?>


<?php
$allowed_guest_checkout = Mage::helper('checkout')->isAllowedGuestCheckout($this->getQuote());
$checkout_method = Mage::getSingleton('checkout/type_onepage')->getCheckoutMethod();
?>
<div class="easy-step" id="easycheckout-addressbilling">
	<h2 class="ter"><?php echo $this->__('Billing Address')?>:</h2>
	
	<ul class="form-list address-form-list">
		
		<?php if ($this->customerHasAddresses()): ?>
        <li>
            <label style="text-align:left;width:auto;float:none;" for="billing-address-select"><?php echo $this->__('Select a billing address from your address book.') ?></label>
            <div>
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
    	<?php endif; ?>
		
	    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?> >
	        <fieldset>
	            <ul <?php if(!$this->isThreeColsMode()):?> class="left" <?php endif;?>>
					<li>
		
						<div class="field name-firstname">
					        <label for="billing:firstname" class="required ehd"><em>*</em><?php echo $this->__('First Name:') ?></label>
					        <div class="input-box">
					            <input type="text" id="billing:firstname" name="billing[firstname]" value="<?php echo $this->getAddress()->getFirstname(); ?>" title="<?php echo $this->__('First Name') ?>" placeholder="<?php echo $this->__('First Name:') ?>" autocomplete="given-name" class="input-text required-entry" />
					        </div>
					    </div>
                        <div class="field name-lastname">
                        	<label for="billing:lastname" class="required ehd"><em>*</em><?php echo $this->__('Last Name:') ?></label>
					        <div class="input-box">
					            <input type="text" id="billing:lastname" name="billing[lastname]" value="<?php echo $this->getAddress()->getLastname(); ?>" title="<?php echo $this->__('Last Name') ?>" placeholder="<?php echo $this->__('Last Name') ?>" autocomplete="family-name" class="input-text required-entry" />
					        </div>
					    </div>
					    
					</li>
					
						<?php if(!$this->isCustomerLoggedIn()): ?>
				        <li>
	                    <div class="field">
	                        <label for="billing:email" class="required ehd"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                        <div class="input-box">
	                            <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>" autocomplete="email" class="input-text validate-email required-entry" />
	                        </div>
	                    </div>
	                    </li>
	                    <?php else:?>
	                    <li>
	                    <div class="field">
	                        <label class="required ehd"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                        <div class="input-box">
	                            <input type="text" name="billing[email]" readonly="readonly" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>" class="input-text readonly" />
	                        </div>
	                    </div>
	                    </li>
			        	<?php endif ?>
					  
                     <li>
						
						<div class="field">
		                    <label for="billing:street1" class="required ehd"><em>*</em><?php echo $this->__('Street line') ?> 1</label>
		                    <div class="input-box">
		                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" placeholder="<?php echo $this->__('Street line') ?> 1" autocomplete="address-line1" class="input-text required-entry" />
		                    </div>
                            <div class="tip"><?php echo $this->__('Note: P.O. box addresses are not available for shipping right now. Please provide street address for your order. Thank you.') ?></div>
		                </div>
					
					</li>
					<li>
						
						<div class="field">
		                	<label for="billing:street2" class="ehd"><?php echo $this->__('Street line') ?> 2</label>
		                    <div class="input-box">
		                        <input type="text" title="<?php echo $this->__('Street Address %s', 2) ?>" name="billing[street][]" id="billing:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" placeholder="<?php echo $this->__('Street line') ?> 2" autocomplete="address-line2" class="input-text" />
		                    </div>
                             <div class="tip"><?php echo $this->__('Example: apartment, suite, unit, building, floor') ?></div>
		                </div>
						
					</li> 
                    
                    <li>
						
						<div class="field">
	                        <label for="billing:city" class="required ehd"><em>*</em><?php echo $this->__('City') ?></label>
	                        <div class="input-box">
	                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" placeholder="<?php echo $this->__('City') ?>" autocomplete="address-level1" class="input-text required-entry" id="billing:city" />
	                        </div>
	                    </div>
						
					</li>    
                        
					<li>
						
						<div class="field">
	                        <label for="billing:country_id" class="required ehd"><em>*</em><?php echo $this->__('Country') ?></label>
	                        <div class="input-box">
	                            <?php echo $this->getCountryHtmlSelect('billing') ?>
	                        </div>
	                    </div>
						
					</li>
					
					<li>
						
						<div class="field">
	                        <label for="billing:region_id" class="required ehd"><em>*</em><?php echo $this->__('State/Province') ?></label>
	                        <div class="input-box">
	                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
	                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
	                            </select>
	                            <script type="text/javascript">
	                            //<![CDATA[
	                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
	                            //]]>
	                            </script>
	                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" placeholder="<?php echo $this->__('State/Province') ?>" autocomplete="address-level2" class="input-text" style="display:none;" />
	                        </div>
	                    </div>
						
					</li>
					
					<li>
						
						<div class="field">
	                        <label for="billing:postcode" class="required ehd"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
	                        <div class="input-box">
	                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" placeholder="<?php echo $this->__('Zip/Postal Code') ?>" autocomplete="postal-code" class="input-text required-entry" />
	                        </div>
	                    </div>
						
					</li>
					
					<li>
						
						<div class="field">
	                        <label for="billing:telephone" class="required ehd"><em>*</em><?php echo $this->__('Telephone') ?></label>
	                        <div class="input-box">
	                            <input type="text" name="billing[telephone]" value="<?php $_tel = $this->getAddress()->getTelephone();
								 $_tel =($_tel)?$_tel:Mage::getSingleton('checkout/session')->getBillingTelephone();
								echo  $this->htmlEscape($_tel);
								 ?>" placeholder="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="billing:telephone" />
	                        </div>
                            <div class="tip"><?php echo $this->__('Your phone number is needed just in case we or the shipping carrier need to reach you regarding your order.') ?></div>
                            
	                    </div>
						
					</li>
					
                    <?php if($this->helper->faxcompanyEnabled()): ?>
					<li>
					
						<div class="field">
	                        <label for="billing:fax" class="ehd"><?php echo $this->__('Fax') ?></label>
	                        <div class="input-box">
	                            <input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" placeholder="<?php echo $this->__('Fax') ?>" class="input-text" id="billing:fax" />
	                        </div>
	                    </div>
						
					</li>
						
					<li>
						
						<div class="field">
	                        <label for="billing:company" class="ehd"><?php echo $this->__('Company') ?></label>
	                        <div class="input-box">
	                            <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" placeholder="<?php echo $this->__('Company') ?>" class="input-text" />
	                        </div>
	                    </div>
						
					</li>
                    <?php endif; ?>
                    
				
				
					
					
					
					
					
					
					
					
					<?php if(!$this->isCustomerLoggedIn()): ?>
		        		<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
						<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
		            	<?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
							<?php if ($_dob->isEnabled()): ?>
								<li>
									<div class="field">
										<?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
									</div>
								</li>
							<?php endif; ?>
							<?php if ($_gender->isEnabled()): ?>
								<li>
									<div class="field">
										<?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
									</div>
								</li>	
							<?php endif ?>
						<?php endif ?>
						<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
						<?php if ($_taxvat->isEnabled()): ?>
						<li>
							<div class="field">
							<?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
							</div>
                            <div class="tip"><?php echo $this->__('CPF/CNPJ,Required for Brazilians') ?></div>
						</li>
						<?php endif ?>
		            	
	                <?php endif; ?>
					
				</ul>
				
			
				<?php if(!$this->isCustomerLoggedIn()): ?>
					<ul>
					
					<?php if(!$this->isCustomerLoggedIn()):?>
						
						<?php if($allowed_guest_checkout):?>
						<li class="control <?php if(!$this->isThreeColsMode()):?>fields<?php endif;?>">
							<div class="field">
								<label for="customer_account_create"><?php echo $this->__('Create Account');?></label>
								<input class="radio" id="customer_account_create" onclick="if(this.checked){$('register-customer-password').style.display='block';}else{$('register-customer-password').style.display='none';}" type="checkbox" <?php if($checkout_method == 'register'):?>checked="checked"<?php endif;?> name="create_account" value="1"  />
							</div>
						</li>
						<?php endif;?>
						
		                <li <?php if(!$this->isThreeColsMode()):?>class="fields"<?php endif;?> id="register-customer-password" <?php if($allowed_guest_checkout && $checkout_method != 'register'):?>style="display:none;"<?php endif;?>>
		                    <div class="field">
		                        <label for="billing_customer_password" class="required ehd"><em>*</em><?php echo $this->__('Password') ?></label>
		                        <div class="input-box">
		                            <input type="password" name="billing[password]" id="billing_customer_password" title="<?php echo $this->__('Password') ?>" placeholder="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
		                        </div>
		                    </div>
		                    <div class="field">
		                        <label for="billing_confirm_password" class="required ehd"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
		                        <div class="input-box">
		                            <input type="password" name="billing[confirmation]" title="<?php echo $this->__('Confirm Password') ?>" id="billing_confirm_password" placeholder="<?php echo $this->__('Confirm Password') ?>" class="input-text required-entry validate-cpassword" />
		                        </div>
		                    </div>
		                </li>
		               	
		               	
		               	
	            	<?php endif; ?>
	            	</ul>
                <?php endif; ?>
	        </fieldset>
	    </li>
	    <?php if($this->isThreeColsMode() && $this->getLayout()->getBlock('checkout.onepage.address.shipping')->canShow()): ?>
			<li>
			 	<label style="width:auto" for="billing_use_for_shipping_yes"><input class="radio" type="checkbox" name="billing[use_for_shipping]" id="billing_use_for_shipping_yes" value="1" <?php if($this->getLayout()->getBlock('checkout.onepage.address.shipping')->someAsBilling()):?> checked="checked" <?php endif;?> class="radio" /><?php echo $this->__('Ship to the same address');?></label>
				
			</li>
		
		<?php endif;?>
	</ul>
	<script type="text/javascript">
	//<![CDATA[
	    
	    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
	    
	//]]>
	</script>
</div>

<?php endif;?>