<?php
    $nofollow='';
	$_filters = $this->getLayer()->getState()->getFilters();
    if(count($_filters)>2)
    $nofollow=' rel="nofollow"';
   
   $_filerName =  $this->getName();
   

?>
<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <li>
            <?php if ($_item->getCount() > 0): ?>
                <?php if(false): ?>
                <input type="checkbox"<?php if ($_item->isSelected()): ?> checked="checked" <?php endif; ?>
                <?php if ($this->helper('ado_seo')->isAjaxEnabled()): ?>
                           onclick="$(this).next().click()"
                       <?php else: ?>
                           onclick="setLocation('<?php  echo ($_item->isSelected()) ? $this->urlEscape($_item->getRemoveUrl()) : $this->urlEscape($_item->getUrl()) ?>')"
                       <?php endif; ?>
                       />
                <?php endif; ?>
                <a<?php if ($_item->isSelected()): ?> onclick="$(this).previous().checked = false;"<?php else: ?> onclick="$(this).previous().checked = true;" 
                    <?php endif; ?>                            
                    href="<?php echo ($_item->isSelected()) ? $_item->getRemoveUrl() : $_item->getUrl() ?>"<?php echo $nofollow;?> title="<?php echo $this->__($_item->getLabel()) ?>"><span class="checkSpan <?php 	
		$bs = str_replace(' ','_',strtolower($_item->getLabel()));
		$bs = str_replace("/",'_',$bs);
		$bs = str_replace("-",'_',$bs);
		echo $bs; ?>"></span><span class="displaySpan <?php 	
		$bs = str_replace(' ','_',strtolower($_item->getLabel()));
		$bs = str_replace("/",'_',$bs);
		$bs = str_replace("-",'_',$bs);
		echo $bs; ?>"><?php echo $this->__($_item->getLabel()) ?>(<?php echo $_item->getCount() ?>)</span></a>
                <?php else: ?>
                    <?php echo $this->__($_item->getLabel()) ?>(<?php echo $_item->getCount() ?>)
                <?php endif; ?>
            
        </li>
    <?php endforeach ?>
</ol>
