<?php
/**
 * This is the part of 'BmProducts' module for Magento,
 * which allows easy access to product collection
 * with flexible filters
 */
?>
<?php 
$_collections = $this->getCatalogRelatedProductCollenction();
if($_collections):
    $_rate=0;
    $_rates = $this->getRate();
    if(!empty($_rates))$_rate=array_unshift($_rates);
    if($_rate>0){
        $title='<span class="block-title-rate">'.$_rate.'%</span>'.$this->__(' bought THIS product after viewing it. Others bought:');
        $title=$this->__('Customers Also Bought');
    }else{
        $title=$this->__('Customers Also Bought');
    }
 ?>
<!-- Catalog Attribute - Related product ids --> 
<div class="block  product-catalog-views-related">
    <div class="block-title"><?php echo $title; ?></div>
    <div class="block-content">     
     <?php $_collectionSize = $_collections->count(); ?>
   <ul class="side-list">
    <?php $i = 1; foreach ($_collections as $_product): ?>
        <li <?php if($i==$_collectionSize) {echo ' class="last"'; } ?>>
                <a class="product-img" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" target="_blank">
                   <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(600, 800) ?>" width="132" height="176" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /> </a>
	       <div class="other-info">
	       <div class="home-name"><h3 class="product-name"><a  href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3></div>
               <?php echo $this->getPriceHtml($_product, true, $this->getPriceSuffix()) ?>
               <?php $old_price = $_product->getPrice();  ?>
							 <?php $special_price = $_product->getFinalPrice();?>
							 <?php $percent = ceil((($old_price-$special_price)/$old_price)*100)?>
							 <?php if($percent){?>
							 <span class="red">save:<?php echo $percent ?>% off</span>
							 <?php }?>
 
	       </div>
        </li>
     <?php $i++; endforeach; ?>
     </ul>
    </div>
</div>
<?php endif; ?>