<?php
/**
 * @var $_product   Mage_Catalog_Model_Product
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$helpZoom = $this->helper('dock_cloudzoom');
$helpImg = $this->helper('dock/image');

//Get image sizes. If height is not specified, aspect ratio will be kept.
$imgWidth = intval($helpZoom->getCfg('images/main_width'));
$imgHeight = intval($helpZoom->getCfg('images/main_height'));
$bigImageWidth = intval($helpZoom->getCfg('general/big_image_width'));
$bigImageHeight = intval($helpZoom->getCfg('general/big_image_height'));
$thumbImgWidth = 72; //intval($helpZoom->getCfg('images/thumbnail_width'));
$thumbImgHeight = 96; //intval($helpZoom->getCfg('images/thumbnail_height'));

//If main image width is not specified, use default values
if ($imgWidth <= 0) {
    $imgWidth = 363;
    $imgHeight = 363;
}

//If main image width is not specified, use default values
if ($bigImageWidth <= 0) {
    $bigImageWidth = 650;
    $bigImageHeight = 650;
}

//Aspect ratio settings
if ($helpZoom->getCfg('images/aspect_ratio')) {
    //Height will be calculated automatically based on width to keep the aspect ratio of each image
    $imgHeight = 0;
    $bigImageHeight = 0;
    $thumbImgHeight = 0;
}
?>

<div class="product-img-box img-box img-box-style1">
    <?php
    $sliderId = "itemslider-zoom";
    $_currentColor = Mage::getSingleton('core/app')->getRequest()->getParam(Ado_SEO_Block_Catalog_Product_List_Colors::COLOR_ATTRIBUTE_CODE,'');
    $defailtSelectedIndex = 0;
    $mainImagePath = ''; // $attr_gallery='';
    $galleryImages = $this->getGalleryImages();
    if (count($galleryImages) > 0) {
        $gallery = '<div class="more-views ado-slidecontent" id="slidecontent45">';
        //$gallery .= '<h2>' . $this->__('More Views') . '</h2>';
        $gallery .= '<div class="ado-navigator-wapper"><div onclick="return false" class="ado-next">&nbsp;</div><div class="ado-navigator-outer">';

        $gallery .= '<ul class="ado-navigator" id="'.$sliderId.'">';

        // 添加属性图片 开始
        //  $attr_gallery = '<div style="display:none" id="ado-navigator"><ul>';
        $i=0;
        foreach ($galleryImages as $_image) {
            if (!$_image->getFile() || $_image->getFile() == 'no_selection') continue;
            $seleted = '';

            if($_currentColor && strcasecmp($_currentColor,$_image->getTitle())===0){
                $defailtSelectedIndex = $i;
                $mainImagePath = $this->getGalleryUrl($_image);
                $seleted = ' class="active"';

            }else if ($_image->getFile() == $_product->getData('small_image')) {
                $mainImagePath = $this->getGalleryUrl($_image);
            }
            $gallery .= '<li'.$seleted.'>'
                .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery lightbox-group" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($thumbImgWidth,$thumbImgHeight) . '" width="62" height="85" data-color="'.$_image->getTitle().'" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                .  '<em class="arrow"></em></a></li>';
            // $gallery .= '<div style="display:none;" id="cloudZoomAs"><img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(170,170) . '"/></div>';
            // $gallery .= '</li>';

            //   $attr_gallery  .= '<li'.$seleted.'>'
            //                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(170,170) . '"  bigsrc="' . $this->getCloudImage($this->getProduct(), $_image) .  '" alt="' . $this->htmlEscape($_image->getLabel()) . '"/>'
            //                 .  '</li>';

            $i++;
        }
        $gallery .= '</ul></div>';

        $gallery .= '<div onclick="return false" class="ado-previous">&nbsp;</div></div></div>';

        // 添加属性图片结束
        //  $attr_gallery .= '</ul></div>';
    }
    ?>
    <?php
    $zoomClasses = '';
    if ($helpZoom->useCloudZoom() == false)
        $zoomClasses .= ' simple-mode';
    else {
        if ($helpZoom->isPositionInside())
            $zoomClasses .= ' zoom-inside';
    }
    ?>
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom<?php echo $zoomClasses; ?>" style=" z-index: 100;">
            <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image',$_currentColor); ?>" class="cloud-zoom lightbox-group" id="cloudZoom">
                <?php
                $_img = '<img id="image" src="'.$this->getCloudImage($_product,$_currentColor).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel($_product,'image',$_currentColor)).'"/>';
                echo $_helper->productAttribute($_product, $_img, 'image');
                ?>
            </a>
            <?php if ($helpZoom->useLightbox()): ?>
                <?php
                $zoomBtnClasses = '';
                if ($helpZoom->useCloudZoom() == false)
                    $zoomBtnClasses .= ' zoom-btn-large';
                else
                    $zoomBtnClasses .= ' zoom-btn-small';
                ?>
                <a id="zoom-btn" class="lightbox-group<?php echo $zoomBtnClasses; ?>"
                   href="<?php echo $helpImg->getImg($_product, $bigImageWidth, $bigImageHeight); ?>"
                   title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>"><?php echo $this->__('Zoom'); ?></a>

            <?php endif; ?>
        </p>

        <?php if(isset($gallery)): ?>
            <?php echo $gallery; ?>
        <?php endif; ?>


    <?php else: ?>
        <p class="product-image" style="max-width: <?php echo $imgWidth; ?>px;">
            <img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight); ?>"
                 alt="<?php echo $this->escapeHtml($this->getImageLabel()); ?>"
                 title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" itemprop="image"/>
        </p>
    <?php endif; ?>

    <script type="text/javascript">
        var currentNo=<?php echo $defailtSelectedIndex; ?>;
    </script>

</div> <!-- end: img-box -->

<?php echo $this->getChildHtml('lightboxConfig'); ?>

<script type="text/javascript">
    //<![CDATA[
    jQuery(function ($) {
        var $cz = $('.cloud-zoom');
        var czInstance = $('.cloud-zoom').data('zoom');
        //On image change
        $(document).on('product-media-manager-image-updated', function (e, data) {

            var img = data.img;

            czInstance.destroy();

            //Add new image's URL to the CloudZoom element's href attribute
            $cz.attr('href', img.attr('src'));

            //Remove mousetrap
            var $mt = $('.mousetrap');
            $mt.unbind();
            $mt.remove();
            $mt = null;

            //Reinitialize CloudZoom
            $cz.CloudZoom();

        }); //end: on event
        //On resize
        var t;
        $(window).resize(function () {
            clearTimeout(t);
            t = setTimeout(function () {

                czInstance.destroy();

                //Remove mousetrap and other elements
                var $mt = $('.mousetrap');
                $mt.unbind();
                $mt.remove();
                $mt = null;
                $('.cloud-zoom-lens').remove();
                $('#cloud-zoom-big').remove();

                //Reinitialize CloudZoom
                $cz.CloudZoom();

            }, 200);
        });
    });
    //]]>
</script>
<?php echo $this->getChildHtml('after'); ?>
