<div class="onepage-footer-container">
    <div style="text-align:center;margin:0 auto;width:100%;" id="footer-tag" >

    </div>
    <div class="footer_bg">
        <div class="copyright" style="text-align:center;">
            <?php echo 'Copyright &copy; 2010 - '.date('Y').'  '.vsprintf('<a href="%s" style="text-transform: lowercase;">%s</a>',array(Mage::getBaseUrl(),ucwords(str_replace(array('http:','/','index.php'),'',Mage::getBaseUrl())))); ?></div>
    </div>
</div>