<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
    <strong class="section-title"><?php echo $this->__('Additional Information') ?></strong>
    <ul id="product-attribute-specs-table" class="product-attribute-specs-table">
        <?php foreach ($_additional as $_data): ?>
           <li class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif;?>
