<?php
	
/*
 * Magento EsayCheckout Extension
 *
 * @copyright:	EcommerceTeam (http://www.ecommerce-team.com)
 * @version:	1.1
 *
 */
	
?>
<script type="text/javascript">
	//<![CDATA[
	var countryRegions			= <?php echo $this->helper('directory')->getRegionJson(); ?>;
	
	var checkoutDefaultUrl		= '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'methods'));?>';
	<?php if($this->helper->shippingFirstEnabled()):?>
	<?php if($this->helper->differentShippingEnabled()):?>
	var checkoutShippingUrl 	= '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'payment'));?>';
	var checkoutBillingUrl  	= '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'billing'));?>';
	<?php else:?>
	var checkoutShippingUrl		= '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'methods'));?>';
	<?php endif;?>
	<?php else:?>
	<?php if($this->helper->differentShippingEnabled()):?>
	var checkoutBillingUrl		= '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'payment'));?>';
	var checkoutShippingUrl		= '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'shipping'));?>';
	<?php else:?>
	var checkoutBillingUrl		= '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'methods'));?>';
	<?php endif;?>
	<?php endif;?>
	var checkoutTotalsUrl		= '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'review'));?>';
	var checkoutCouponUrl		= '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'coupon'));?>';
	
	
	var loginFormHtml = '<div id="elogin-message" class="a-left"></div>'+
		'<ul class="form-list">'+
            '<li>'+
                '<label class="required" for="elogin-email"><em>*</em><?php echo $this->__('Email Address');?></label>'+
                '<div class="input-box"><input type="text" title="<?php echo $this->__('Email Address');?>" class="input-text" id="elogin-email" /></div>'+
            '</li>'+
            '<li>'+
                '<label class="required" for="elogin-password"><em>*</em><?php echo $this->__('Password');?></label>'+
                '<div class="input-box"><input type="password" title="<?php echo $this->__('Password');?>" class="input-text" id="elogin-password"/></div>'+
            '</li>'+
        '</ul>'+
        '<div class="actions">'+
        	'<div id="elogin-buttons">'+
	        	'<div class="left">'+
	        		'<a href="<?php echo $this->getUrl('customer/account/forgotpassword')?>"><?php echo $this->__('Forgot Your Password?')?></a>'+
	        	'</div>'+
	        	'<div class="right">'+
	        		'<button class="button" onclick="TINY.box.hide();return false;"><span><span><?php echo $this->__('Cancel');?></span></span></button>'+
	        		'<button style="margin-left:5px;" class="button" onclick="elogin($(\'elogin-email\').value, $(\'elogin-password\').value, \'<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'login'));?>\');return false;"><span><span><?php echo $this->__('Login');?></span></span></button>'+
	        	'</div>'+
	        '</div>'+
        	'<div id="elogin-loading" style="display:none;"><?php echo $this->__('loading please wait...');?></div>'+
        '</div>';
	
	
	//]]>
</script>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<!-- Check Step Title S -->
<div class="page-title title-buttons">
<h1><?php echo $this->__('Check');?></h1>
</div>
<!-- Check Step Title E -->
======
<div class="easycheckout-onepage-wrap easycheckout-1column" id="easycheckout-form-wrap">
	
	<div id="load-info-overlay">&nbsp;</div>
	
	<?php echo $this->getCmsBlockHtml();?>
	
	<?php if(!Mage::helper('customer')->isLoggedIn()): ?>
	
	<p class="already-go"><a href="<?php echo $this->getUrl('customer/account/login');?>" onclick="TINY.box.show(loginFormHtml,0,260,0,0);return false"><?php echo $this->__('Already registered? Click here to login.');?></a></p>
	
	<?php endif;?>
	
	<form action="<?php echo $this->getUrl('*/*/save');?>" method="post" id="easycheckout-form">
		
        <?php if($this->helper->shippingFirstEnabled()): ?>
        <?php if(!$this->getQuote()->isVirtual()): ?>
		<?php echo $this->getChildHtml('shipping_address'); ?>
		<?php endif; ?>
		<?php echo $this->getChildHtml('billing_address'); ?>		
        <?php else: ?>
		<?php echo $this->getChildHtml('billing_address'); ?>
		<?php if(!$this->getQuote()->isVirtual()):?>
		<?php echo $this->getChildHtml('shipping_address'); ?>
		<?php endif; ?>
        <?php endif; ?>
		
	
	    <!-- /echeckout/ -->	
        <div id="easycheckout-shipping-payment-step">
			<?php if(!$this->getQuote()->isVirtual()):?>
				<div class="shipping-method"><?php echo $this->getChildHtml('shipping_method');?></div>
				<div class="methods-separator">&nbsp;</div>
			<?php endif;?>
		</div>
        
        <?php echo $this->getChildHtml('review');?>
		
		<?php if($this->helper->couponEnabled()):?>
			<div id="easycheckout-coupon" class="easy-step">
				<?php echo $this->getChildHtml('echeckout_coupon');?>
			</div>
		<?php endif;?>
		
		<div id="easycheckout-payment-method-available" class="payment-method"><?php echo $this->getChildHtml('payment_method');?></div>
		<div id="easycheckout-totals"><?php echo $this->getChildHtml('echeckout_totals'); ?></div>
		<div class="button-set">
			
			<?php if($this->helper->showSubscribe()):?>
			
			<p><label><input type="checkbox" name="subscribe" value="1"/> <?php echo $this->__('Subscribe to newsletter');?></label></p>
			
			<?php endif;?>
			
			
			<button id="submit-btn" type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
			
			
		</div>
		
	</form>
</div>
	
	
<script type="text/javascript">
	//<![CDATA[
	var checkoutForm = new VarienForm('easycheckout-form');
	
	checkoutForm.validator.options.onFormValidate = function(result, form) {
		if(result){
			$('submit-btn').disabled = 'disabled';
			$('submit-btn').addClassName('btn-checkout-disabled');
		}
		
	};
	
	//]]>
</script>

<?php
   $total=$this->getQuote()->getBaseGrandTotal();
   if(!$total)$total='180.00';
?>
<!-- Google Code for &#21435;&#25903;&#20184; Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 972798139;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "leG3CJ2O-gsQu_HuzwM";
var google_conversion_value = <?php echo $total; ?>;
var google_conversion_currency = "USD";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/972798139/?value=<?php echo $total; ?>&amp;currency_code=USD&amp;label=leG3CJ2O-gsQu_HuzwM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<!--bing code--->
<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"4001835"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script>

<!-- Facebook Conversion Code for yeahmobi-checkouts -->
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6023680958826', {'value':'0.00','currency':'USD'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6023680958826&amp;cd[value]=0.00&amp;cd[currency]=USD&amp;noscript=1" /></noscript>
<!-- Facebook Conversion Code for yeahmobi-checkouts -->